### ISSUE TITLE
RegEx support for redirects

### ISSUE THREAD

**Issue by manniL** [netlify/ask-netlify#28]
## About me

- **My name:** is still Alex 😋 
- **I've used Netlify:** excessively

## My question in a little more detail

I really enjoy the `redirect` system and the idea of *splats* and *placeholders*. However, I  feel like sometimes it'd be useful to have more freedoms to customize redirects.

Especially I'm missing that we can't use regular expressions to match (and re-insert) URLs or query variables as you can with `Apache`, `Nginx` or even other Netlify competitors.

Will there be RegEx support for redirect rules in the future *or* would you suggest using a custom function instead? 🤔

**Comment by ericmarcos** [comment]
Is this available already? I couldn't find any documentation.

**Comment by manniL** [comment]
@ericmarcos 	I don't think so.

**Comment by j-f1** [comment]
It looks like they never finished episode 3 :(

**Comment by andre-brdoch** [comment]
It would be great if something like this would be possible:
```
/:dir/*.pdf /:dir/:splat 301!
```

**Comment by ddamato** [comment]
I actually have a more involved use-case. It would look something like this

/dir/:pdf.pdf /api/tracker?pdf=:pdf
/dir/:pdf https://bucket.s3.amazonaws.com/dir/:pdf.pdf

So basically, the redirects handle a proxy to the API in order to track the number of times the file was requested. I used to do this with Apache but I think if the tokens were a little more strict here it could work.

**Comment by philsturgeon** [comment]
I want to redirect from 

/api/2018/04/13/openapi-and-json-schema-divergence-solved

to

/2018/openapi-and-json-schema-divergence-solved

but that doesnt seem possible with the * and splat...

**Comment by j-f1** [comment]
```
/api/:year/:month/:day/:slug    /:year/:slug
```
