### ISSUE TITLE
What does the "Free Plan" on Netlify really give me?

### ISSUE THREAD

**Issue by talves** [netlify/ask-netlify#6]
## About me

- **My name:** Tony Alves
- **I've used Netlify:** Tons

## My question in a little more detail

Where to start? I **think** I understand fully, but wonder a lot about how it all fits together when I am running multiple pet projects through Netlify with some supported client projects also.

- Bandwidth
- Storage
- Number of sites
- Identity explained (maybe too big for this answer)
- Deploys
- How can Netlify give this all away for free?

## Anything other comments for Netlify

People really don't believe me when I tell them they get all the soft limits and they are paying so much for their shared hosting. I think in one of the talks at the JAMStack_conf there was mention of perception of prices equating to better services. 😩

> There has to be hidden costs. --Pessimist Friend

This answer really needs to be somewhere I can just send all these people to.

**Comment by DirtyF** [comment]
Free plan limitations are listed here: https://www.netlify.com/tos/ (well hidden if you ask me)

**Comment by talves** [comment]
Thanks Frank 😜It is more of a rhetorical question, but good to have the link if someone reads this.

> People really don't believe me when I tell them they get all the soft limits and they are paying so much for their shared hosting.

**Comment by DirtyF** [comment]
@talves you're welcome 😄 

Ask your friend if he pays to get an email address or 15GB of free space on Google 😜 
Why would he pay for some megabytes fo static files on a CDN?
And if he really wants to pay, there are paid plans, he'll get premium support!

Of course, they are costs, but those costs are supposed to be absorbed by paying customers.
It's also about getting to know the service before becoming a proper customer.
Once you're hooked on Netlify, you're more wiling to pay for the service —I admit, I've become a "Netliholic".

It's called the freemium model, and there's only one catch: catching big projects.

**Comment by talves** [comment]
Exactly. There was a talk at the JAMStack conference where they were joking about pricing. Some customers just need to see a big price tag to think it has value. I guess if they want to pay for a service that is free, we should give it to them (premium).

Explaining the whole stack and the reason for these changes of how they will pay for services is going to be a challenge at first for customers. Fun times ahead.

Of course, I am a Netlify fan. You are preaching to the choir here.

**Comment by hail2thief** [comment]
Following-up here: what happens if I go over "Free tier" soft limits? I don't expect to, but I'm wondering how Netlify deals with this given I don't even have a credit card on file that can be used to automatically move me into "Paid tier". I worry about my course site being restricted in some way mid-semester.

**Comment by tyleryoungblood** [comment]
It seems like if you have an event that puts you over the free-tier limits, Netlify will ask you to update your billing information and add a CC. I assume if you already have a CC on file, Netlify will probably just bill you for the overage for that month. 

An example would be:

- adding a second member (+ $15/user/mo) 
- exceeding the 100GB limit (+ $20/mo/100GB)
- exceeding the free 100 form submissions limit per month (+ $19/month/site for 1,000 submissions - Level 0 to Level 1 tier). 

We just had this happen and our site didn't stop working. We just received notification that we needed up update our billing, which was nice because this caused us to take a look at what caused the increase in billing and decide if we wanted to make a change or pay the extra amount. 

One thing I'm not sure about is if you stay at the increased tier moving forward. Meaning, if you have 101 form submissions and get bumped from Level 0 to Level 1 forms, do you start the following month back at Level 0 or Level 1? I can see how a smaller sight might have one or two months a year where they exceed the free limits but would otherwise be fine with the free tier. My hope is that Netlify would do the right thing and return them to the free tier at the start of each month. But I'm not sure.

So far I've been totally impressed with Netlify. I just wish they had a forum solution. :)

**Comment by talves** [comment]
@tyleryoungblood https://community.netlify.com

**Comment by tyleryoungblood** [comment]
Sorry, I didn't realize this was a closed issue. I was simply trying to answer hail2thief's answer above. :)

**Comment by talves** [comment]
No problem at all, the message is more for future too. 😜

**Comment by vdiaza** [comment]
Hi all, anybody knows if the netlify quotas are per account or per site, especially for the forms.
I am building a site for a friend/client and I wonder if i keep his site on my account would affect my other sites so maybe it would be better to create an account for my client.

**Comment by talves** [comment]
@vdiaza Start at this thread: https://community.netlify.com/t/pricing-and-plans/257/40

You can always send an email to support to clarify, but asking the specific question in the community will help others with the same question.
